pipeline_config:
  # 取得存放在 Secret Manager key 為 postgres_master 對應的 Value
  source_credentials: postgres_master
  s3_bucket_name: datalakepractice
  ingestion_table_list: ['orders']


tables:
  - customers:
    destination_table: customers
    export_file_name: customers.parquet
    s3_file_path: crm/customers/in
    column_inclusions: [
       'customer_id',
       'first_name',
       'last_name',
       'email',
       'phone'
    ]
    update_method: incremental_load
    incremental_load_columns: ['created_at', 'updated_at']
    copy_extra_params: "CSV DELIMITER AS ',' IGNOREHEADER 1 NULL AS 'NULL'"
    day_load_duration: "'7 days'"
    column_to_extract: ['customer_id', 'first_name', 'last_name', 'email']

  - products:
    destination_table: products
    export_file_name: products.parquet
    s3_file_path: crm/products/in
    column_inclusions: [
       'product_id',
       'product_name',
       'price'
    ]
    update_method: incremental_load
    incremental_load_columns: ['created_at', 'updated_at']
    day_load_duration: "'7 days'"
    column_to_extract: ['product_id', 'product_name', 'price']

  - orders:
    destination_table: orders
    export_file_name: orders.parquet
    s3_file_path: crm/orders/in
    column_inclusions: [
       'customer_id',
       'first_name',
       'last_name',
       'email',
       'phone'
    ]
    update_method: incremental_load
    incremental_load_columns: ['created_at', 'updated_at']
    day_load_duration: "'7 days'"
    column_to_extract: ['order_id', 'total_amount']

  - order_items:
    destination_table: order_items
    export_file_name: order_items.parquet
    s3_file_path: crm/order_items/in
    column_inclusions: [
       'order_item_id',
       'order_id',
       'product_id',
       'quantity',
       'price'
    ]
    update_method: incremental_load
    incremental_load_columns: ['created_at', 'updated_at']
    day_load_duration: "'7 days'"
    column_to_extract: ['order_item_id', 'quantity', 'price']
    